// <auto-generated />
namespace OPBids.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class parsefullnameofaccessuserstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(parsefullnameofaccessuserstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903171407040_parse fullname of accessusers table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
