// <auto-generated />
namespace OPBids.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class supplier_adduserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(supplier_adduserid));
        
        string IMigrationMetadata.Id
        {
            get { return "201903240529281_supplier_adduserid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
