// <auto-generated />
namespace OPBids.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class access_users_profile_link : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(access_users_profile_link));
        
        string IMigrationMetadata.Id
        {
            get { return "201904150153529_access_users_profile_link"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
